version : '2'
services:
  ngtesting-postgres:
    image: registry.cn-shanghai.aliyuncs.com/ngtesting/ngtesting-postgres:2.0.0
    environment:
      - POSTGRES_PASSWORD=P2ssw0rd
    ports:
      - "55432:5432"

  ngtesting-web:
    image: registry.cn-shanghai.aliyuncs.com/ngtesting/ngtesting-web:2.0.0
    depends_on:
      - ngtesting-postgres
    ports:
      - "58080:8080"
    command: ["/wait-for-it.sh", "ngtesting-postgres:5432", "-t", "10", "--", "/setup.sh", "--", "/usr/bin/java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/ngtesting-web.jar", "--spring.profiles.active=docker"]
