name: make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: install dependencies
#      run: go get all

    - name: make server
      run: make compile_server_linux

    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
            SSH_PRIVATE_KEY: ${{ secrets.DT_PRIVATEKEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "bin/linux/deeptest-server"
            REMOTE_HOST: ${{ secrets.DT_SERVER }}
            REMOTE_USER: ${{ secrets.DT_USERNAME }}
            TARGET: "/home/lighthouse/rd/project/deeptest/bin/linux"
            EXCLUDE: ""
            SCRIPT_BEFORE: |
              whoami
              mkdir -p /home/lighthouse/rd/project/deeptest/bin/linux
              ls -al /home/lighthouse/rd/project/deeptest/bin/linux
            SCRIPT_AFTER: |
              whoami
              ls -al /home/lighthouse/rd/project/deeptest/bin/linux
              echo $RSYNC_STDOUT
