name: make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: go get all

    - name: make server
      run: make compile_server_linux

    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.1.8
